### ISSUE TITLE
Plugin dont work in Intellij 2021.2

### ISSUE THREAD

**Issue by marioserrano09** [zkoss/zkidea#28]

**Comment by cor3000** [comment]
stack trace:
![image_2021_07_28T09_54_03_394Z](https://user-images.githubusercontent.com/3894309/127303527-1811097b-def1-4ef4-b8a7-94e9edede680.png)

**Comment by cor3000** [comment]
first error about path to xsd
https://github.com/zkoss/zkidea/blob/28e29a6a8fe399a631614e1133d03154a7365c61/src/main/java/org/zkoss/zkidea/lang/ZulSchemaProvider.java#L30

second about path to maven archetype catalog:
https://github.com/zkoss/zkidea/blob/28e29a6a8fe399a631614e1133d03154a7365c61/src/main/java/org/zkoss/zkidea/maven/ZKMavenArchetypesProvider.java#L36
