### ISSUE TITLE
Plugin V0.1.22 does not work properly with IntelliJ  V2023.3.6 (Ultimate)

### ISSUE THREAD

**Issue by klauswr** [zkoss/zkidea#42]
After each restart of IntelliJ the zul support (color coding, auto-complete, ...) is disabled. 
The only way to reestablish the support is to "disable apply" and "enable apply" the plugin. 

This did not happen with V0.1.21 - but after installing V0.1.22 even if I reinstall the older version V0.1.21 now the problem persists.

**Comment by jumperchen** [comment]
This issue seems like this one - https://github.com/zkoss/zkidea/issues/39#issuecomment-1712703493
If so, you can use that workaround to fix this issue.

**Comment by klauswr** [comment]
Unfortunately, the workaround #39 does not work for me.

**Comment by klauswr** [comment]
After having upgraded to IntelliJ Idea 2024.1 the problem still persisted. 
But then I did the following: 
In Settings -> Editor -> File Types -> XML
1. remove *.zul  as File name pattern
2. add *.zul as new File name pattern again

Now it works. I don't know why.
