### ISSUE TITLE
Needed to disable/enable plugin after start of Intellij Idea to have plugin working

### ISSUE THREAD

**Issue by mikealdo** [zkoss/zkidea#43]
Hi, plugin is not loaded for .zul files when Intellij Idea starts. When I disable plugin, apply change and then enable and apply it's working.

Idea 2024.1.1
Build #IU-241.15989.150, built on April 29, 2024

**Comment by jumperchen** [comment]
Fyi, https://github.com/zkoss/zkidea/issues/42#issuecomment-2059670503 or https://github.com/zkoss/zkidea/issues/39#issuecomment-1712703493

**Comment by mikealdo** [comment]
Thanks. #42 works for me.
